In [ ]:
import numpy as np

# NumPy
## Basis
### Built-in Functions

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("arr: ", arr)

zeros = np.zeros((2, 3))
print("zeros: ", zeros)

ones = np.ones((2, 3))
print("ones: ", ones)

range_arr = np.arange(0, 10, 2)
print("range: ", range_arr)

linspace = np.linspace(0, 10, 5)
print("linspace: ", linspace)

arr:  [1 2 3 4 5 6]
zeros:  [[0. 0. 0.]
 [0. 0. 0.]]
ones:  [[1. 1. 1.]
 [1. 1. 1.]]
range:  [0 2 4 6 8]
linspace:  [ 0.   2.5  5.   7.5 10. ]


### Operations
- Element-wise Operations
- Math Operations

In [ ]:
arr.reshape((3, 2)) # Allow change shape of array, length should be get by (a, b)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a + b: ", a + b)
print("a - b: ", a - b)
print("a * b: ", a * b)
print("a / b: ", a / b)

print("." * 10)

c = np.array([2, 4, 9, 16, 25])
print("sqrt(c): ", np.sqrt(c))
print("sin(c): ", np.sin(c))
print("log(c): ", np.log(c))

print("." * 10)

d = np.array([1, 2, 3])
e = np.array([4, 5, 6])
print("dot(d, e): ", np.dot(d, e))

print("." * 10)

f = np.array([1, 3, 4, 5, 6, 8, 8, 9])
print("mean", np.mean(f))
print("median", np.median(f))
print("std", np.std(f))
print("var", np.var(f))
print("max", np.max(f))
print("min", np.min(f))

print("." * 10)

g = np.array([[1, 2, 3], [4, 6, 7], [1, 4, 6]])
print(g.T)
print(g.T * g)

a + b:  [5 7 9]
a - b:  [-3 -3 -3]
a * b:  [ 4 10 18]
a / b:  [0.25 0.4  0.5 ]
..........
sqrt(c):  [1.41421356 2.         3.         4.         5.        ]
sin(c):  [ 0.90929743 -0.7568025   0.41211849 -0.28790332 -0.13235175]
log(c):  [0.69314718 1.38629436 2.19722458 2.77258872 3.21887582]
..........
dot(d, e):  32
..........
mean 5.5
median 5.5
std 2.598076211353316
var 6.75
max 9
min 1
..........
[[1 4 1]
 [2 6 4]
 [3 7 6]]
[[ 1  8  3]
 [ 8 36 28]
 [ 3 28 36]]


### Advanced Operations
- Broadcasting
- Filtering
- Aggregation

In [ ]:
print(a + g) # [1, 2, 3] + [[1, 2, 3] [4, 6, 7] [1, 4, 6]]
print(g[g % 2 == 0])
print(g.sum(axis=0))
print(g.sum(axis=1))

[[ 2  4  6]
 [ 5  8 10]
 [ 2  6  9]]
[2 4 6 4 6]
[ 6 12 16]
[ 6 17 11]


# Pandas

In [ ]:
import pandas as pd

In [ ]:
series = pd.Series(["Jean", "Maria", "Paul", "Thomas"])
data = pd.DataFrame({"Name": ["Gabriela", "David"], "Age": [18, 30], "Status": ["Active", "Inactive"]})

print(series)
print(".."*10)
print(data)

0      Jean
1     Maria
2      Paul
3    Thomas
dtype: object
....................
       Name  Age    Status
0  Gabriela   18    Active
1     David   30  Inactive


In [ ]:
df_houses = pd.read_csv("sample_data/california_housing_test.csv")

In [ ]:
print(df_houses.info())
print(df_houses.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB
None
         longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000   
mean   -119.589200    35.63539           28.845333   2599.578667   
std       1.994936     2.12967           12.555396   2155.593332   
min    -124.180000    32.56000      

In [ ]:
print(df_houses.head())
print(df_houses.tail())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  
      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14

In [ ]:
print("Select: ", df_houses[["total_rooms", "total_bedrooms"]])
print("Filter: ", df_houses[(df_houses["total_rooms"] > 300) & (df_houses["population"] > 300)])
print("Position by Column: ", df_houses.iloc[0])
print("Position by Label: ", df_houses.loc[0])

Select:        total_rooms  total_bedrooms
0          3885.0           661.0
1          1510.0           310.0
2          3589.0           507.0
3            67.0            15.0
4          1241.0           244.0
...           ...             ...
2995       1450.0           642.0
2996       5257.0          1082.0
2997        956.0           201.0
2998         96.0            14.0
2999       1765.0           263.0

[3000 rows x 2 columns]
Filter:        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
4       -119.67     36.33                19.0       1241.0           244.0   
5       -119.56     36.51                37.0       1018.0           213.0   
...         ...       ...                 ...          ...             ...   
299