# NumPy
## Basis
### Built-in Functions

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("arr: ", arr)

zeros = np.zeros((2, 3))
print("zeros: ", zeros)

ones = np.ones((2, 3))
print("ones: ", ones)

range_arr = np.arange(0, 10, 2)
print("range: ", range_arr)

linspace = np.linspace(0, 10, 5)
print("linspace: ", linspace)

arr:  [1 2 3 4 5 6]
zeros:  [[0. 0. 0.]
 [0. 0. 0.]]
ones:  [[1. 1. 1.]
 [1. 1. 1.]]
range:  [0 2 4 6 8]
linspace:  [ 0.   2.5  5.   7.5 10. ]


### Operations
- Element-wise Operations
- Math Operations

In [3]:
arr.reshape((3, 2)) # Allow change shape of array, length should be get by (a, b)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a + b: ", a + b)
print("a - b: ", a - b)
print("a * b: ", a * b)
print("a / b: ", a / b)

print("." * 10)

c = np.array([2, 4, 9, 16, 25])
print("sqrt(c): ", np.sqrt(c))
print("sin(c): ", np.sin(c))
print("log(c): ", np.log(c))

print("." * 10)

d = np.array([1, 2, 3])
e = np.array([4, 5, 6])
print("dot(d, e): ", np.dot(d, e))

print("." * 10)

f = np.array([1, 3, 4, 5, 6, 8, 8, 9])
print("mean", np.mean(f))
print("median", np.median(f))
print("std", np.std(f))
print("var", np.var(f))
print("max", np.max(f))
print("min", np.min(f))

print("." * 10)

g = np.array([[1, 2, 3], [4, 6, 7], [1, 4, 6]])
print(g.T)
print(g.T * g)

a + b:  [5 7 9]
a - b:  [-3 -3 -3]
a * b:  [ 4 10 18]
a / b:  [0.25 0.4  0.5 ]
..........
sqrt(c):  [1.41421356 2.         3.         4.         5.        ]
sin(c):  [ 0.90929743 -0.7568025   0.41211849 -0.28790332 -0.13235175]
log(c):  [0.69314718 1.38629436 2.19722458 2.77258872 3.21887582]
..........
dot(d, e):  32
..........
mean 5.5
median 5.5
std 2.598076211353316
var 6.75
max 9
min 1
..........
[[1 4 1]
 [2 6 4]
 [3 7 6]]
[[ 1  8  3]
 [ 8 36 28]
 [ 3 28 36]]


### Advanced Operations
- Broadcasting
- Filtering
- Aggregation

In [5]:
print(a + g) # [1, 2, 3] + [[1, 2, 3] [4, 6, 7] [1, 4, 6]]
print(g[g % 2 == 0])
print(g.sum(axis=0))
print(g.sum(axis=1))

[[ 2  4  6]
 [ 5  8 10]
 [ 2  6  9]]
[2 4 6 4 6]
[ 6 12 16]
[ 6 17 11]
